config/routes.rb
JqueryDms::Application.routes.draw do
  resources :documents, :except => [:edit, :update, :show]
  root :to => 'documents#index'
end

app/models/document.rb
class Document < ActiveRecord::Base
  mount_uploader :file, FileUploader

  include Rails.application.routes.url_helpers

  validates :file, :presence => true

  before_validation do
    self.name = self.file.to_readable_name
  end

  scope :choices, select([:"#{table_name}.id", :"#{table_name}.name"]).order(:"#{table_name}.name")
  scope :match_with, lambda { |name| where("documents.name LIKE \"%#{name}%\"") }

  #one convenient method to pass jq_upload the necessary information
  def to_jq_upload(show_checkbox = false)
    {
        "id" => self.id,
        "name" => self.name.humanize,
        #"size" => file.size.to_i,
        "url" => file.url,
        "full_path" => file.current_path,
        "delete_url" => document_path(:id => id),
        "delete_type" => "DELETE",
        "show_checkbox" => show_checkbox
    }
  end

  def self.search(p)
    return match_with(p[:name]) if p[:name].present?
    all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  def index
    @documents = Document.search(params)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @documents.collect { |p| p.to_jq_upload }.to_json }
    end
  end

  def new
    @object_new = Document.new
  end

  def create
    @document = Document.new
    @document.file = params[:document][:path]

    if @document.save
      respond_to do |format|
        format.html { redirect_to documents_path, :notice => 'Document uploaded successfully' }
        format.json { render :json => [@document.to_jq_upload(true)].to_json }
      end
    else
      render :json => [{:error => "custom_failure"}], :status => 304
    end
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_path }
      format.json { render :json => true }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_search.html.erb
<div class="pull-right">
  <%= form_tag documents_path, :method => :get do %>
      <div class="input-append">
        <%= search_field_tag :name, params[:name], :placeholder => 'search', :class => "span2 auto_search_complete" %>
        <%= button_tag "Search", :name => nil, :class => 'btn', :id => "btn_search" %>
        <input type="reset" class="reset-search btn" value="Reset" />
      </div>
  <% end %>
</div>

app/views/documents/index.html.haml
#fileupload.file-gallery
  %h4{:class => 'pull-left'} Documents
  = render "documents/search"

  %table.table.table-striped
    %tbody.files{"data-toggle" => "modal-gallery",  "data-target" => "#modal-gallery"}
      = render "shared/fileupload/queue"
      - if @documents.empty?
        %tr
          %td.empty
            There is no document.
            = link_to 'Click here', new_document_path
            to upload new file.
      - else
        = render "shared/fileupload/index"

- content_for :javascript do
  :javascript
    initializeUploaderWithFiles(true);

app/views/documents/new.html.haml
%h4 Upload document(s)
.span9.file-gallery
  = render "shared/fileupload"

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")

    %title= content_for?(:title) ? yield(:title) : 'Document Management System'
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements

    /[if lt IE 7]
      = stylesheet_link_tag "http://blueimp.github.com/cdn/css/bootstrap-ie6.min.css"
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"

    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'

    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    = favicon_link_tag 'favicon.ico'

  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to(t("Document Management System"), root_path, :class => "brand")
          .container.nav-collapse
            %ul.nav.pull-right
              %li= link_to 'Upload New', new_document_path

    .container
      .content
        = render "shared/flash_messages"
        = yield

    .container
      %footer

    = yield :javascript

app/views/shared/_fileupload.html.erb
<%= form_for @object_new, :html => {:multipart => true, :id => "fileupload"} do |f| %>
    <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
    <div class="row fileupload-buttonbar">
      <div class="span7">
        <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="icon-plus icon-white"></i>
                    <span><%= t('fileupload.add_files') %></span>
                  <%= f.file_field :path %>
                </span>
        <button type="submit" class="btn btn-primary start">
          <i class="icon-upload icon-white"></i>
          <span><%= t('fileupload.start_upload') %></span>
        </button>
        <button type="reset" class="btn btn-warning cancel">
          <i class="icon-ban-circle icon-white"></i>
          <span><%= t('fileupload.cancel_upload') %></span>
        </button>
        <button type="button" class="btn btn-danger delete">
          <i class="icon-trash icon-white"></i>
          <span><%= t('fileupload.delete_multi') %></span>
        </button>
        <input type="checkbox" class="toggle">
      </div>
      <div class="span5">
        <!-- The global progress bar -->
        <div class="progress progress-success progress-striped active fade">
          <div class="bar" style="width:0%;"></div>
        </div>
      </div>
    </div>
    <!-- The loading indicator is shown during image processing -->
    <div class="fileupload-loading"></div>
    <br>
    <!-- The table listing the files available for upload/download -->
    <table class="table table-striped">
      <tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
    </table>
<% end %>

<%= render "shared/fileupload/queue" %>
<%= render "shared/fileupload/index" %>

<script type="text/javascript" charset="utf-8">
    initializeUploaderWithFiles(false, "<%=@object_new.file.extension_white_list.join('|')%>");
</script>

app/views/shared/_flash_messages.html.haml
- flash.each do |type, message|
  %div{:class => "alert alert-#{{:notice => :info, :alert => :error}[type] || type}"}
    %a.close{:"data-dismiss" => "alert"}
      &times;
    = message